<!doctype html>
<html lang="en">
    <?php
        $root = $request->getUri()->getBaseUrl();

        $prevweek = $week - 1;
        $nextweek = $week + 1;

        if( $week - 1 == 0 )
            $prevweek = '../' . ( intval( substr( $year, -2, 2 ) ) - 2 ) . '-' . ( intval( substr( $year, -2, 2 ) ) - 1 ) . '/52';
        else if( $week + 1 == 53 )
            $nextweek = '../' . ( intval( substr( $year, -2, 2 ) ) + 1 ) . '-' . ( intval( substr( $year, -2, 2 ) ) + 2 ) . '/1';
    ?>
    <head>
        <meta charset="utf-8">
        <meta name="description"
              content="What's cookin' at the student restaurant at UCLL's campus Proximus today?">
        <meta name="keywords"
              content="ucll, uc, leuven, limburg, campus, proximus, restaurant, cafetaria, horeservice, omnomnom">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="format-detection"
              content="telephone=no">

        <title>ProxiResto</title>

        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $root; ?>/public/assets/img/_icons/icon.ico">
        <link rel="icon" type="image/png" href="<?php echo $root; ?>/public/assets/img/_icon/icons.png">

        <link rel="stylesheet" media="screen" href="<?php echo $root; ?>/public/assets/css/screen.css">
        <link rel="stylesheet" media="print" href="<?php echo $root; ?>/public/assets/css/print.css">
    </head>

    <body style="background-image: url('<?php echo $root; ?>/public/assets/img/_backgrounds/bg<?php echo date( 'g' ); ?>.jpg')">
        <script type="text/javascript">
            document.body.className = "loading";
        </script>

        <header>
            <section id="top">
                <a href="<?php echo $root; ?>" class="internal">
                    <h1>Student restaurant <span>Campus Proximus</span></h1>
                </a>
                <div id="hamburger"><span>&nbsp;</span></div>
            </section>
        </header>

        <main>
            <section id="menu" class="swiper-wrapper">
                <h2 class="h">Menu of the week</h2>

                <article id="monday" class="swiper-slide hide">
                    <h3>Monday
                        <time
                                datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['1'] ) ): ?>
                        <?php if( !empty( $menu['1']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['1']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo utf8_encode( $soup['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['1']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['1']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo utf8_encode( $dish['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['1']['snack'] ) ): ?>
                            <ul class="snack">
                                <?php foreach( $menu['1']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo utf8_encode( $snack['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant closed
                        </p>
                    <?php endif; ?>
                </article>
                <article id="tuesday" class="swiper-slide hide">
                    <h3>Tuesday
                        <time
                                datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 1 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 1 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['2'] ) ): ?>
                        <?php if( !empty( $menu['2']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['2']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo utf8_encode( $soup['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['2']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['2']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo utf8_encode( $dish['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['2']['snack'] ) ): ?>
                            <ul class="snack">
                                <?php foreach( $menu['2']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo utf8_encode( $snack['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant closed
                        </p>
                    <?php endif; ?>
                </article>
                <article id="wednesday" class="swiper-slide hide">
                    <h3>Wednesday
                        <time
                                datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 2 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 2 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['3'] ) ): ?>
                        <?php if( !empty( $menu['3']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['3']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo utf8_encode( $soup['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                              &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['3']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['3']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo utf8_encode( $dish['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['3']['snack'] ) ): ?>
                            <ul class="snack">
                                <?php foreach( $menu['3']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo utf8_encode( $snack['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant closed
                        </p>
                    <?php endif; ?>
                </article>
                <article id="thursday" class="swiper-slide hide">
                    <h3>Thursday
                        <time
                                datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 3 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 3 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['4'] ) ): ?>
                        <?php if( !empty( $menu['4']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['4']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo utf8_encode( $soup['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['4']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['4']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo utf8_encode( $dish['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['4']['snack'] ) ): ?>
                            <ul class="snack">
                                <?php foreach( $menu['4']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo utf8_encode( $snack['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant closed
                        </p>
                    <?php endif; ?>
                </article>
                <article id="friday" class="swiper-slide hide">
                    <h3>Friday
                        <time
                                datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 4 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 4 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['5'] ) ): ?>
                        <?php if( !empty( $menu['5']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['5']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo utf8_encode( $soup['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['5']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['5']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo utf8_encode( $dish['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['5']['snack'] ) ): ?>
                            <ul class="snack">
                                <?php foreach( $menu['5']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo utf8_encode( $snack['name_en'] ); ?>
                                        <span
                                                data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                                data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarian dish">Vegetarian dish</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant closed
                        </p>
                    <?php endif; ?>
                </article>
            </section>

            <section id="prefs">
                <h2 class="h">About ProxiResto</h2>

                <article>
                    <h3>Preferences</h3>
                    <ul>
                        <li>
                            <input id="box_cookie" type="checkbox">
                            <label for="box_cookie">Allow cookies</label>
                        </li>
                        <li class="needcookie disabled">
                            <input id="box_price" type="checkbox" checked disabled>
                            <label for="box_price">Show student prices</label>
                        </li>
                        <li class="needcookie disabled">
                            <select id="sel_lang" disabled>
                                <option value="en">English</option>
                                <option value="nl">Nederlands</option>
                            </select>
                            <span id="opt_lang">nl</span>
                            <label for="sel_lang">Preferred language</label>
                        </li>
                        <li id="set_lang" class="needcookie disabled">
                            <a href="<?php echo $root; ?>" class="internal">Apply language now</a>
                        </li>
                    </ul>
                    <p class="note">
                        Your preferred language will be used if the display language is not defined in the web address.
                    </p>
                </article>

                <article class="mobile">
                    <h3>Web application</h3>
                    <ul>
                        <li>
                            <a href="<?php echo $root; ?>/en/app">How to install</a>
                        </li>
                    </ul>
                </article>

                <article>
                    <h3>Disclaimer</h3>
                    <ul>
                        <li>
                            <a id="lnk_contact" target="_blank" href="http://m.me/Qrivi">Report bug or issue</a>
                        </li>
                        <li>
                            <a id="lnk_donate" target="_blank" href="https://www.paypal.me/Qrivi">Treat developer a
                                                                                                  sandwich</a>
                        </li>
                    </ul>
                    <p class="note">
                        ProxiResto is a side project and in no way affiliated with UCLL, HoreServi or any other third
                        parties. Data is provided by UCLL's intranet and may be erroneous. ProxiResto is not accountable
                        for long waiting queues at the restaurant. Enjoy your meal!
                    </p>
                </article>
            </section>

            <section id="contact">
                <h2 class="h">Contact the developer</h2>

                <ul>
                    <li class="twitter">
                        <a href="http://twitter.com/ProxiResto" target="_blank" title="Twitter">Twitter</a>
                    </li>
                    <li class="mail">
                        <a href="mailto:kristof-DOT-dewilde-AT-student-DOT-ucll-DOT-be" title="Email">Email</a>
                    </li>
                    <li class="messenger">
                        <a href="http://m.me/ProxiResto" target="_blank" title="Messenger">Messenger</a>
                    </li>
                </ul>
                <button class="dismiss">
                    <span>Dismiss</span>
                </button>
            </section>

            <div class="swiper-pagination hide"></div>
        </main>

        <footer class="hide">
            <nav>
                <ul>
                    <li class="prev">
                        <a id="lnk_prev" href="<?php echo $prevweek; ?>"><span>Previous week</span></a>
                    </li>
                    <li class="next">
                        <a id="lnk_next" href="<?php echo $nextweek; ?>"><span>Next week</span></a>
                    </li>
                </ul>
            </nav>
        </footer>

        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $root; ?>/public/assets/js/page.js"></script>
        <script type="text/javascript" src="<?php echo $root; ?>/public/assets/js/extra.js"></script>
        <script type="text/javascript">var root = '<?php echo $root;?>';</script>

        <script>
            (function( i, s, o, g, r, a, m ){
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function(){
                        (i[r].q = i[r].q || []).push( arguments )
                    }, i[r].l = 1 * new Date();
                a = s.createElement( o ),
                    m = s.getElementsByTagName( o )[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore( a, m )
            })( window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga' );

            ga( 'create', 'UA-85600402-1', 'auto' );
            ga( 'send', 'pageview' );

        </script>
    </body>
</html>