<!doctype html>
<html lang="nl">
    <?php
        $root = $request->getUri()->getBaseUrl();

        $prevweek = $week - 1;
        $nextweek = $week + 1;

        if( $week - 1 == 0 )
            $prevweek = '../' . ( intval( substr( $year, -2, 2 ) ) - 2 ) . '-' . ( intval( substr( $year, -2, 2 ) ) - 1 ) . '/52';
        else if( $week + 1 == 53 )
            $nextweek = '../' . ( intval( substr( $year, -2, 2 ) ) + 1 ) . '-' . ( intval( substr( $year, -2, 2 ) ) + 2 ) . '/1';
    ?>
    <head>
        <meta charset="utf-8">
        <meta name="description"
              content="Wat schaft de pot vandaag in het studentenrestaurant van UCLL's campus Proximus?">
        <meta name="keywords"
              content="ucll, uc, leuven, limburg, campus, proximus, restaurant, cafetaria, horeservice, omnomnom">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui">
        <meta name="apple-mobile-web-app-capable"
              content="yes">
        <meta name="apple-mobile-web-app-status-bar-style"
              content="default">
        <meta name="format-detection"
              content="telephone=no">

        <title>ProxiResto</title>

        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $root; ?>/public/assets/img/icon.ico">
        <link rel="icon" type="image/png" href="<?php echo $root; ?>/public/assets/img/icon.png">

        <link rel="stylesheet" media="screen" href="<?php echo $root; ?>/public/assets/css/screen.css">
    </head>

    <body style="background-image: url('<?php echo $root; ?>/public/assets/img/bg<?php echo date( 'g' ); ?>.jpg')">

        <header>
            <section id="top">
                <a href="<?php echo $root; ?>" class="internal">
                    <h1>Studentenrestaurant <span>Campus Proximus</span></h1>
                </a>
                <div id="hamburger"><span>&nbsp;</span></div>
            </section>
        </header>

        <main>
            <section id="menu" class="swiper-wrapper">
                <h2 class="h">Menu van de week</h2>

                <article id="maandag" class="swiper-slide hide">
                    <h3>Maandag
                        <time
                            datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['1'] ) ): ?>
                        <?php if( !empty( $menu['1']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['1']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo $soup['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['1']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['1']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo $dish['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['1']['snack'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['1']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo $snack['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant gesloten
                        </p>
                    <?php endif; ?>
                </article>
                <article id="dinsdag" class="swiper-slide hide">
                    <h3>Dinsdag
                        <time
                            datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 1 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 1 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['2'] ) ): ?>
                        <?php if( !empty( $menu['2']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['2']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo $soup['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['2']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['2']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo $dish['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['2']['snack'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['2']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo $snack['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant gesloten
                        </p>
                    <?php endif; ?>
                </article>
                <article id="woensdag" class="swiper-slide hide">
                    <h3>Woensdag
                        <time
                            datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 2 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 2 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['3'] ) ): ?>
                        <?php if( !empty( $menu['3']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['3']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo $soup['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                              &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['3']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['3']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo $dish['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['3']['snack'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['3']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo $snack['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant gesloten
                        </p>
                    <?php endif; ?>
                </article>
                <article id="donderdag" class="swiper-slide hide">
                    <h3>Donderdag
                        <time
                            datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 3 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 3 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['4'] ) ): ?>
                        <?php if( !empty( $menu['4']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['4']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo $soup['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['4']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['4']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo $dish['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['4']['snack'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['4']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo $snack['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant gesloten
                        </p>
                    <?php endif; ?>
                </article>
                <article id="vrijdag" class="swiper-slide hide">
                    <h3>Vrijdag
                        <time
                            datetime="<?php echo date( 'Y-m-d', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 4 day' ) ); ?>">
                            <?php echo date( 'j/n', strtotime( $year . 'W' . sprintf( '%02d', $week ) . '+ 4 day' ) ); ?></time>
                    </h3>
                    <?php if( !empty( $menu['5'] ) ): ?>
                        <?php if( !empty( $menu['5']['soup'] ) ): ?>
                            <ul class="soup">
                                <?php foreach( $menu['5']['soup'] as $soup ): ?>
                                    <li>
                                        <?php echo $soup['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $soup['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $soup['price'], 2, ',', ' ' ); ?>
                                        </span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['5']['dish'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['5']['dish'] as $dish ): ?>
                                    <li>
                                        <?php echo $dish['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $dish['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $dish['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $dish['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php if( !empty( $menu['5']['snack'] ) ): ?>
                            <ul class="dish">
                                <?php foreach( $menu['5']['snack'] as $snack ): ?>
                                    <li>
                                        <?php echo $snack['name']; ?>
                                        <span
                                            data-students="&euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>"
                                            data-external="&euro; <?php echo number_format( $snack['price_ext'], 2, ',', ' ' ); ?>">
                                            &euro; <?php echo number_format( $snack['price'], 2, ',', ' ' ); ?>
                                        </span>
                                        <?php if( intval( $snack['veggie'] ) > 0 ): ?>
                                            <aside class="veg" title="Vegetarische schotel">Vegetarische schotel</aside>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php else: ?>
                        <p>
                            Restaurant gesloten
                        </p>
                    <?php endif; ?>
                </article>
            </section>

            <section id="prefs" class="">
                <h2 class="h">Over ProxiResto</h2>

                <article>
                    <h3>Voorkeuren</h3>
                    <ul>
                        <li>
                            <input id="box_cookie" type="checkbox">
                            <label for="box_cookie">Cookies toestaan</label>
                        </li>
                        <li class="needcookie disabled">
                            <input id="box_price" type="checkbox" checked disabled>
                            <label for="box_price">Studentenprijzen tonen</label>
                        </li>
                        <li class="needcookie disabled">
                            <select id="sel_lang" disabled>
                                <option value="nl">Nederlands</option>
                                <option value="en">English</option>
                            </select>
                            <span id="opt_lang">nl</span>
                            <label for="sel_lang">Voorkeurstaal</label>
                        </li>
                        <li class="needcookie disabled temporary">
                            <a href="<?php echo $root; ?>" class="internal">Taal meteen toepassen</a>
                        </li>
                    </ul>
                    <p class="note">
                        Je voorkeurstaal wordt gebruikt wanneer je gewenste taal niet in het webadres vermeld wordt.
                    </p>
                </article>

                <article class="mobile">
                    <h3>Webapplicatie</h3>
                    <ul>
                        <li>
                            <a href="<?php echo $root; ?>/app">Installatie-instructies</a>
                        </li>
                    </ul>
                </article>

                <article>
                    <h3>Vrijwaringsclausule</h3>
                    <ul>
                        <li>
                            <a id="lnk_contact" target="_blank" href="http://m.me/Qrivi">Probleem of fout melden</a>
                        </li>
                        <li>
                            <a id="lnk_donate" target="_blank" href="https://www.paypal.me/Qrivi">
                                Developer broodje trakteren</a>
                        </li>
                    </ul>
                    <p class="note">
                        ProxiResto is een vrijetijdsproject en is niet geaffilieerd met UCLL, HoreServi of andere
                        derden. Data is afkomstig van UCLL's intranet en kan incorrect zijn. ProxiResto is niet
                        verantwoordelijk voor lange files in het restaurant. Smakelijk!
                    </p>
                </article>
            </section>

            <section id="contact">
                <h2 class="h">Contacteer de developer</h2>

                <ul>
                    <li class="twitter">
                        <a href="http://twitter.com/Qrivi" target="_blank" title="Twitter">Twitter</a>
                    </li>
                    <li class="mail">
                        <a href="mailto:kristof-DOT-dewilde-AT-student-DOT-ucll-DOT-be" title="E-mail">E-mail</a>
                    </li>
                    <li class="messenger">
                        <a href="http://m.me/Qrivi" target="_blank" title="Messenger">Messenger</a>
                    </li>
                </ul>
                <button class="dismiss">
                    <span>Annuleren</span>
                </button>
            </section>

            <div class="swiper-pagination hide"></div>
        </main>

        <footer class="hide">
            <nav>
                <ul>
                    <li class="prev">
                        <a id="lnk_prev" href="<?php echo $prevweek; ?>"><span>Vorige week</span></a>
                    </li>
                    <li class="next">
                        <a id="lnk_next" href="<?php echo $nextweek; ?>"><span>Volgende week</span></a>
                    </li>
                </ul>
            </nav>
        </footer>

        <script type="text/javascript">
            document.body.className = "loading";
        </script>
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $root; ?>/public/assets/js/page.js"></script>
    </body>
</html>